### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'artifcats_path'

### ISSUE THREAD

**Issue by skearnes** [nak/pytest_mproc#5]
Seems like a typo that should have been caught by automated tests before deploying to PyPI?

```shell
Starting Global.Manager server ('localhost', 59379)...
Started Global.Manager server.
Starting orchestration on localhost:42289
Traceback (most recent call last):
  File "/builds/relaytx/mldc/relay-mldc/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 164, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pytest_mproc/plugin.py", line 266, in pytest_cmdline_main
    config.ptmproc_orchestrator = LocalOrchestrator(project_config=config.ptmproc_config.project_config)
  File "/builds/relaytx/mldc/relay-mldc/venv/lib/python3.10/site-packages/pytest_mproc/main.py", line 419, in __init__
    artifacts_dir=project_config.artifcats_path
AttributeError: 'NoneType' object has no attribute 'artifcats_path'
```

**Comment by DahanDv** [comment]
I experienced the same error when trying to use the plugin

**Comment by nak** [comment]
Added proper check
